export const DEGREE_OPTIONS = [
  { value: "BTECH", label: "B.Tech" },
  { value: "MTECH", label: "M.Tech" },
  { value: "MBA", label: "MBA" },
  { value: "MSC", label: "M.Sc" },
  { value: "PHD", label: "PhD" },
];

export const DEPARTMENT_OPTIONS = {
  BTECH: [
    "COMPUTER SCIENCE AND ENGINEERING",
    "INFORMATION TECHNOLOGY",
    "ELECTRONICS AND COMMUNICATION ENGINEERING",
    "ELECTRICAL ENGINEERING",
    "MECHANICAL ENGINEERING",
    "CIVIL ENGINEERING",
    "INSTRUMENTATION AND CONTROL ENGINEERING",
    "BIO TECHNOLOGY",
    "CHEMICAL ENGINEERING",
    "INDUSTRIAL AND PRODUCTION ENGINEERING",
    "MATHEMATICS AND COMPUTING",
    "TEXTILE TECHNOLOGY",
  ],
  MTECH: [
    // BIO TECHNOLOGY
    "BIO TECHNOLOGY",

    // CHEMICAL ENGINEERING
    "CHEMICAL ENGINEERING",

    // CIVIL ENGINEERING
    "STRUCTURAL AND CONSTRUCTION ENGINEERING",
    "GEOTECHNICAL AND GEO-ENVIRONMENTAL ENGINEERING",

    // COMPUTER SCIENCE AND ENGINEERING
    "COMPUTER SCIENCE AND ENGINEERING",
    "COMPUTER SCIENCE AND ENGINEERING (INFORMATION SECURITY)",
    "DATA SCIENCE AND ENGINEERING",

    // ELECTRICAL ENGINEERING
    "ELECTRIC VEHICLE DESIGN",

    // ELECTRONICS AND COMMUNICATION ENGINEERING
    "SIGNAL PROCESSING AND MACHINE LEARNING",
    "VLSI DESIGN",

    // INDUSTRIAL AND PRODUCTION ENGINEERING
    "INDUSTRIAL ENGINEERING AND DATA ANALYTICS",

    // INFORMATION TECHNOLOGY
    "DATA ANALYTICS",

    // CONTROL AND INSTRUMENTATION ENGINEERING
    "CONTROL AND INSTRUMENTATION ENGINEERING",
    "MACHINE INTELLIGENCE AND AUTOMATION",

    // MATHEMATICS AND COMPUTING
    "MATHEMATICS AND COMPUTING",

    // MECHANICAL ENGINEERING
    "DESIGN ENGINEERING",
    "THERMAL AND ENERGY ENGINEERING",

    // TEXTILE TECHNOLOGY
    "TEXTILE TECHNOLOGY",
    "TEXTILE ENGINEERING AND MANAGEMENT",

    // RENEWABLE ENERGY
    "RENEWABLE ENERGY",

    // ARTIFICIAL INTELLIGENCE
    "ARTIFICIAL INTELLIGENCE",

    // POWER SYSTEMS AND RELIABILITY
    "POWER SYSTEMS AND RELIABILITY",
  ],

  MBA: ["HUMANITIES AND MANAGEMENT"],
  MSC: ["PHYSICS", "CHEMISTRY", "MATHEMATICS"],
  PHD: [],
};

export const JOB_TYPE_OPTIONS = ["Intern", "Intern+PPO", "Intern+FTE", "FTE"];

export const INTERNSHIP_DURATION_OPTIONS = [
  "2m Intern",
  "6m Intern",
  "11m Intern",
];

export const JOB_CATEGORY_OPTIONS = ["Tech", "Non-Tech", "Tech+Non-Tech"];

export const JOB_SECTOR_OPTIONS = ["Private", "PSU"];
